<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.22621.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <RootNamespace>MicaPDF</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <PublishProfile>win-$(Platform).pubxml</PublishProfile>
    <UseWinUI>true</UseWinUI>
    <EnableMsixTooling>true</EnableMsixTooling>
    <Nullable>enable</Nullable>
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <SelfContained>false</SelfContained>
    <PublishReadyToRun Condition="'$(PublishReadyToRun)' == ''">false</PublishReadyToRun>
    <TieredCompilation>true</TieredCompilation>
    <AssemblyName>MicaPDF</AssemblyName>
    <ApplicationIcon>MicaPDF.ico</ApplicationIcon>
    <Version>2.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Graphics.Win2D" Version="1.4.0" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.260804001" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.7705" />
    <PackageReference Include="PdfPig" Version="0.1.15" />
    <PackageReference Include="PDFsharp" Version="6.2.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="MicaPDF.Tests\**" />
    <Content Remove="MicaPDF.Tests\**" />
    <None Remove="MicaPDF.Tests\**" />
    <EmbeddedResource Remove="MicaPDF.Tests\**" />
    <Page Remove="MicaPDF.Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="MicaPDF.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Strings\**\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>
</Project>
